"""vessel_registry_module2

Revision ID: 1330580e428d
Revises: b1c2d3e4f5a6
Create Date: 2026-04-23 00:52:33.683795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1330580e428d'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel_ownership_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('owner_egn', sa.String(length=20), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # users.inspector_id already Integer in the live DB — skip that alteration

    with op.batch_alter_table('vessel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_bg', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('name_en', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('port_registration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gross_tonnage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('owner_egn', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('length',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('width',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_vessel_international_number', ['international_number'])

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('vessel', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vessel_international_number', type_='unique')
        batch_op.alter_column('width',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('owner_egn')
        batch_op.drop_column('gross_tonnage')
        batch_op.drop_column('status')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('port_registration')
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_bg')

    op.drop_table('vessel_photo')
    op.drop_table('vessel_ownership_history')
    op.drop_table('vessel_document')

