"""Add vessel table

Revision ID: 839f889a1f56
Revises: 1118bc600bf1
Create Date: 2026-03-12 23:43:57.636035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839f889a1f56'
down_revision = '1118bc600bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('international_number', sa.String(length=50), nullable=False),
    sa.Column('call_sign', sa.String(length=50), nullable=False),
    sa.Column('marking', sa.String(length=50), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('engine_power', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('captain_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessel')
    # ### end Alembic commands ###
